In [256]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

In [257]:
df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [258]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [259]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [260]:
df['gender'] = [0 if gender=='Male' else 1 for gender in df['gender']]

In [261]:
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,1,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,0,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,0,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,0,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,1,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,0,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,1,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,1,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,0,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,0,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [262]:
df=df.drop('customerID', axis=1)

In [263]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,0,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,0,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,0,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,1,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,1,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,1,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,0,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,0,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [264]:
df['Partner'] = [0 if x=='No' else 1 for x in df['Partner']]

In [265]:
df['Dependents'] = [0 if x=='No' else 1 for x in df['Dependents']]

In [266]:
df['PhoneService'] = [0 if x=='No' else 1 for x in df['PhoneService']]

In [267]:
df['InternetService'] = [0 if x=='DSL' else 1 for x in df['InternetService']]

In [268]:
df['OnlineSecurity'] = [0 if x=='No' else 1 for x in df['OnlineSecurity']]

In [269]:
df['OnlineBackup'] = [0 if x=='No' else 1 for x in df['OnlineBackup']]

In [270]:
df['DeviceProtection'] = [0 if x=='No' else 1 for x in df['DeviceProtection']]

In [271]:
df['TechSupport'] = [0 if x=='No' else 1 for x in df['TechSupport']]

In [272]:
df['StreamingTV'] = [0 if x=='No' else 1 for x in df['StreamingTV']]

In [273]:
df['StreamingMovies'] = [0 if x=='No' else 1 for x in df['StreamingMovies']]

In [274]:
df['Contract'] = [0 if x=='OneYear' else 1 for x in df['Contract']]

In [275]:
df['PaperlessBilling'] = [0 if x=='No' else 1 for x in df['PaperlessBilling']]

In [276]:
df['Churn'] = [0 if x=='No' else 1 for x in df['Churn']]

In [277]:
df['MultipleLines'] = [0 if x=='No phone service' else 1 if x=='Yes' else 2 for x in df['MultipleLines']]

In [278]:
df['PaymentMethod'] = [0 if x=='Electronic check' else 1 if x=='Mailed check' else 2 if x=='Bank transfer (automatic)' else 3 for x in df['PaymentMethod']]

In [279]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,1,1,0,29.85,29.85,0
1,0,0,0,0,34,1,2,0,1,0,1,0,0,0,1,0,1,56.95,1889.5,0
2,0,0,0,0,2,1,2,0,1,1,0,0,0,0,1,1,1,53.85,108.15,1
3,0,0,0,0,45,0,0,0,1,0,1,1,0,0,1,0,2,42.30,1840.75,0
4,1,0,0,0,2,1,2,1,0,0,0,0,0,0,1,1,0,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,1,1,24,1,1,0,1,0,1,1,1,1,1,1,1,84.80,1990.5,0
7039,1,0,1,1,72,1,1,1,0,1,1,0,1,1,1,1,3,103.20,7362.9,0
7040,1,0,1,1,11,0,0,0,1,0,0,0,0,0,1,1,0,29.60,346.45,0
7041,0,1,1,0,4,1,1,1,0,0,0,0,0,0,1,1,1,74.40,306.6,1
7042,0,0,0,0,66,1,2,1,1,0,1,1,1,1,1,1,2,105.65,6844.5,0

In [280]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [281]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

df['TotalCharges'] = df['TotalCharges'].astype(float)

In [282]:
df['TotalCharges'].unique()

array([  29.85, 1889.5 ,  108.15, ...,  346.45,  306.6 , 6844.5 ])

In [283]:
# df = df.drop('TotalCharges', axis=1)

In [284]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,1,1,0,29.85,29.85,0
1,0,0,0,0,34,1,2,0,1,0,1,0,0,0,1,0,1,56.95,1889.50,0
2,0,0,0,0,2,1,2,0,1,1,0,0,0,0,1,1,1,53.85,108.15,1
3,0,0,0,0,45,0,0,0,1,0,1,1,0,0,1,0,2,42.30,1840.75,0
4,1,0,0,0,2,1,2,1,0,0,0,0,0,0,1,1,0,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,1,1,24,1,1,0,1,0,1,1,1,1,1,1,1,84.80,1990.50,0
7039,1,0,1,1,72,1,1,1,0,1,1,0,1,1,1,1,3,103.20,7362.90,0
7040,1,0,1,1,11,0,0,0,1,0,0,0,0,0,1,1,0,29.60,346.45,0
7041,0,1,1,0,4,1,1,1,0,0,0,0,0,0,1,1,1,74.40,306.60,1
7042,0,0,0,0,66,1,2,1,1,0,1,1,1,1,1,1,2,105.65,6844.50,0

In [285]:
df.isnull().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [286]:
X = df.drop(columns=['Churn'])
y = df['Churn']

In [287]:
X

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,1,1,0,29.85,29.85
1,0,0,0,0,34,1,2,0,1,0,1,0,0,0,1,0,1,56.95,1889.50
2,0,0,0,0,2,1,2,0,1,1,0,0,0,0,1,1,1,53.85,108.15
3,0,0,0,0,45,0,0,0,1,0,1,1,0,0,1,0,2,42.30,1840.75
4,1,0,0,0,2,1,2,1,0,0,0,0,0,0,1,1,0,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,1,1,24,1,1,0,1,0,1,1,1,1,1,1,1,84.80,1990.50
7039,1,0,1,1,72,1,1,1,0,1,1,0,1,1,1,1,3,103.20,7362.90
7040,1,0,1,1,11,0,0,0,1,0,0,0,0,0,1,1,0,29.60,346.45
7041,0,1,1,0,4,1,1,1,0,0,0,0,0,0,1,1,1,74.40,306.60
7042,0,0,0,0,66,1,2,1,1,0,1,1,1,1,1,1,2,105.65,6844.50

In [288]:
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [289]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [290]:
X_train

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
2142,1,0,0,1,21,1,2,0,1,0,1,0,0,1,1,0,1,64.85,1336.80
1623,1,0,0,0,54,1,1,1,0,1,0,0,1,1,1,1,2,97.20,5129.45
6074,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,1,0,23.45,23.45
1362,0,0,0,0,4,1,2,1,0,0,0,0,0,0,1,1,0,70.20,237.95
6754,0,0,0,1,0,1,1,0,1,1,0,1,0,0,1,1,2,61.90,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,0,0,1,0,1,1,2,1,1,0,0,0,1,1,1,1,0,95.00,95.00
5191,1,0,1,1,23,1,1,0,1,1,1,1,1,1,1,1,3,91.10,2198.30
5226,0,0,1,1,12,1,2,1,1,1,1,1,1,1,1,1,0,21.15,306.05
5390,0,1,0,0,12,1,1,1,0,0,1,0,1,1,1,1,0,99.45,1200.15
860,0,0,0,0,26,1,2,1,1,1,1,1,1,1,1,0,3,19.80,457.30

In [291]:
len(y_train)

5634

In [292]:
X_test.shape

(1409, 19)

In [293]:
len(y_test)

1409

In [294]:
clf = DecisionTreeClassifier(random_state=42)

In [295]:
clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [296]:
y_pred = clf.predict(X_test)

In [298]:
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.7132718239886444

In [299]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,1,0,1,0,1,0,0,0,0,1,0,0,0,0,1,1,0,29.85,29.85,0
1,0,0,0,0,34,1,2,0,1,0,1,0,0,0,1,0,1,56.95,1889.50,0
2,0,0,0,0,2,1,2,0,1,1,0,0,0,0,1,1,1,53.85,108.15,1
3,0,0,0,0,45,0,0,0,1,0,1,1,0,0,1,0,2,42.30,1840.75,0
4,1,0,0,0,2,1,2,1,0,0,0,0,0,0,1,1,0,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,0,0,1,1,24,1,1,0,1,0,1,1,1,1,1,1,1,84.80,1990.50,0
7039,1,0,1,1,72,1,1,1,0,1,1,0,1,1,1,1,3,103.20,7362.90,0
7040,1,0,1,1,11,0,0,0,1,0,0,0,0,0,1,1,0,29.60,346.45,0
7041,0,1,1,0,4,1,1,1,0,0,0,0,0,0,1,1,1,74.40,306.60,1
7042,0,0,0,0,66,1,2,1,1,0,1,1,1,1,1,1,2,105.65,6844.50,0

In [302]:
trial = [[1, 1, 0, 1, 30, 0, 2, 1, 1, 0, 0,1, 0, 1, 1, 0, 0, 103.10, 1830]]

In [303]:
new = clf.predict(trial)

C:\Users\vasco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [304]:
new

array([1], dtype=int64)